language: node_js # elm is installed from npm (see install below)
node_js: node     # use "latest" version of Node.js

env:
  - ELM_VERSION=0.18.0 
  - ELM_TEST=0.18.12

cache:
  directories: # so subsequent builds run faster
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - tests/elm-stuff/build-artifacts # elm-test init creates a "tests/" dir
    - tests/elm-stuff/packages        # cache files that haven't changed
    - sysconfcpus
    - $HOME/.npm # https://stackoverflow.com/a/42523517/1148249

before_install:
  - | # build time improvement see: https://git.io/vQcqz
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install: # install specific versions of elm & elm-test
  - npm install -g elm@$ELM_VERSION elm-test@$ELM_TEST elm-format@exp
  # the next 3 lines are courtesy of @rtfeldman https://git.io/vbj0j
  - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
  - printf "#\041/bin/bash\n\necho \"Running elm-make with sysconfcpus -n 2\"\n\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old \"\$@\"" > $(npm config get prefix)/bin/elm-make
  - chmod +x $(npm config get prefix)/bin/elm-make
  - travis_retry elm package install --yes # install main project dependencies

script:
  - make

deploy:
  provider: pages
  local-dir: output
  target-branch: gh-pages
  skip-cleanup: true
  github-token: 
    secure: "kvSEjGFQLm8P+MjnRsn536Hi1Qsdsv7K2libk65JdS4VjEOZwv9rnpdFDf7LD7W9LIHAxDDZ19FkN8yDiuwgrLFsctbR8glba9isTPlvRHIJ75KmOetgzJWyntMFiJQcDVfd5nZDEsnJXvZOHPEp/I79oIC82MwOQDvaLr6Y9Kqe6OaMXeabkoTswhFWd2CE8EaiextM4UFeigdNPTsRUkmq6ofgAgSQ5EXqRSy83hu0pGAkNEwcRn9KE/d5x72neF2N3ZJfgPc8xjhUoc+acNhGBxQ6iEkLRPfsLF0+2cA/WzsC7EYrnKAN2pUG1KkwWS3Uluyd2TayMj2ja7DRZwLEcdzoetG2dzN+GtHJexwHDzeC9fEDJE1pabUx85M8MA77HfWKxfYn3fMEA4dwunlptg+5tRH14+M7JmWtQdg1fGr7Pg4G/8kGAi6Na5eKXW6rc52/DtUIwirs12QXOPwL98clLTE8JnNqR/7BCcBGu6KGyztEHZ4aII2Bx8ejvAyRxb6Qogadenaa+foiMIxwgdO18P6gJ+fmEADaYgo3ebkY6C0pF6Eh6k7BdlTSRGTBfAWP0+7ojJKPkCctwPiSCRm/Re1mV90w74AE0PBQ2tO4iBEAbvnOOcBRHeVgTGoJ2b8AZADjUCLoxzxyVlWqur9FmBCDeiSnVf0xyY8="
  keep-history: true
  on:
    branch: master
